# -*- coding: utf-8 -*-
"""Copy of svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CDD11Cu8zuJtJz3-rFb7sKNBCZMFvRQ
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# data set ni load chesam sir
iris = datasets.load_iris()
X = iris.data
y = iris.target

# training data ni test data ni separate chestam ikkada
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# mana svm classifier ki data 0 to 1 madaylo undali so scaling ()
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# mana model
model = SVC(kernel='linear', C=1.0)
model.fit(X_train, y_train)

# tseting
predictions = model.predict(X_test)

print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions, target_names=iris.target_names))

weights = model.coef_
weights

import numpy as np
#inputs must be in hex format

# 1. Configuration
# We multiply by 256 (2^8) to shift the decimal point 8 places to the right
FRACTIONAL_BITS = 8
SCALE = 2**FRACTIONAL_BITS
b_s = 2**16

def to_hex(val, bits):
    """Converts a signed integer to a hex string for Verilog."""
    return format(val & (2**bits - 1), f'0{bits//4}x')

# 2. Extract and Scale SVM Parameters (One-vs-One: 3 classifiers)
weights = np.round(model.coef_ * SCALE).astype(int)
biases = np.round(model.intercept_ * b_s).astype(int)

# 3. Extract and Scale Scaler Parameters (Mean and 1/Std)
means = np.round(sc.mean_ * SCALE).astype(int)
inv_std = np.round((1.0 / np.sqrt(sc.var_)) * SCALE).astype(int)

# 4. Generate Verilog Parameters
#print("// Paste these into your Vivado Verilog File\n")
print(f"// Scaler Parameters (Q8.8)")
for i in range(4):
    print(f"parameter signed [15:0] MEAN_{i} = 16'h{to_hex(means[i], 16)};")
    print(f"parameter signed [15:0] INV_STD_{i} = 16'h{to_hex(inv_std[i], 16)};")

print(f"\n// SVM Weights and Biases (Q8.8)")
for i in range(3):
    print(f"// Classifier {i}")
    for j in range(4):
        print(f"parameter signed [15:0] W{i}_{j} = 16'h{to_hex(weights[i,j], 16)};")
    print(f"parameter signed [31:0] B{i} = 32'h{to_hex(biases[i], 32)};")



